[tool.poetry]
name = "document_image_utils"
version = "0.1.4"
description = "Toolkit for document image processing"
authors = ["Gonçalo Afonso <brazafonso2001@gmail.com>"]
readme = "README.md"
packages = [
    { include = "document_image_utils" }
]

[tool.poetry.dependencies]
python = "^3.10.11"
opencv-python = "^4.9.0.80"
scipy = "^1.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"